name: Build And Push Docker Image

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/build-and-push-docker-image
      with:
        registry_username: ${{secrets.DOCKERHUB_USERNAME}}
        registry_password: ${{secrets.DOCKERHUB_TOKEN}}
